easy_admin:
   entities:
        User:
            class: App\Entity\User
        Property:
            class: App\Entity\Property
        Option:
            class: App\Entity\Option
        Picture:
            class: App\Entity\Picture
        Event:
            class: App\Entity\Event
